### ISSUE TITLE
Implement search command as wizard

### ISSUE THREAD

**Issue by rmpestano** [rmpestano/music-addon#14]
Implement Initial step to configure filters and next step to show a list (UISelect) of songs found and then play selected songs

**Comment by rmpestano** [comment]
@gastaldi any hint why 'next' button is not enabled in the [this wizard](https://github.com/rmpestano/music-addon/blob/master/src/main/java/com/github/forge/addon/music/ui/SearchCommand.java#L221)?

I can send a message to user list if you want

**Comment by gastaldi** [comment]
Probably because isGui() returns false in your scenario? Also, why are you
checking that?
Em 23/10/2015 14:03, "Rafael M. Pestano" <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
Another reason is because you might have some validation failures
Em 23/10/2015 14:12, "George Gastaldi" <ggastald@redhat.com> escreveu:

**Comment by gastaldi** [comment]
Hm. But that is not the case, as you are not validating anything
explicitly. Let me try to reproduce it locally
Em 23/10/2015 14:13, "George Gastaldi" <ggastald@redhat.com> escreveu:

**Comment by rmpestano** [comment]
I've removed isGui and 'next' is still disabled.

My envoromnent here at work(win8) is a bit strange, eg every time I execute 'build and install addon' I have to restart the IDE otherwise the commands of the installed addon dont show up. I have removed forge home but didnt helped.

**Comment by gastaldi** [comment]
This is a known issue: https://issues.jboss.org/browse/FORGE-2200. We
believe it's because Windows is locking files. We'll need some help on
debugging this.

On Fri, Oct 23, 2015 at 2:33 PM, Rafael M. Pestano <notifications@github.com
> wrote:

> I've removed isGui and 'next' is still disabled.
>
> My envoromnent here at work(win8) is a bit strange, eg every time I
> execute 'build and install addon' I have to restart the IDE otherwise the
> commands of the installed addon dont show up. I have removed forge home but
> didnt helped.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmpestano/music-addon/issues/14#issuecomment-150626946>
> .
>



-- 
*George Gastaldi | Senior Software Engineer*

JBoss Forge Team
T: +55 11 3524-6169
M: +55 47 9711-1000

**Comment by gastaldi** [comment]
I found it why. That's because you don't have any Input added in the initializeUI() method in SearchCommandStep.
I believe you forgot  to call `builder.add(songsFound)`

**Comment by gastaldi** [comment]
Another way to share attributes (instead of using the Attribute map in UIContext) is to create a @CommandScoped POJO and @Inject it in both steps.

**Comment by rmpestano** [comment]
Yea, that was the issue, thanks again.

One thing that is not working is that in the resulting step, the UISelectMany<Song> comes empty:

![search-step](https://cloud.githubusercontent.com/assets/1592273/10703390/a33be32e-79ae-11e5-9564-fc1c77429550.png)

I'm using IDEA here, I'll try with eclipse later

**Comment by rmpestano** [comment]
Hi @gastaldi, almost there, its working great on eclipse(and console) but in IDEA  the @CommandScoped seems to not be working:

WELD-001303: No active contexts for scope type org.jboss.forge.addon.ui.cdi.CommandScoped

**Comment by gastaldi** [comment]
I'll try to reproduce next week and fix it.
Thanks for reporting this
Em 24/10/2015 08:44, "Rafael M. Pestano" <notifications@github.com>
escreveu:

**Comment by rmpestano** [comment]
:thumbsup:

**Comment by gastaldi** [comment]
Looks like the IDEA plugin is not calling the registered `UIContextListener` objects
Here is an example in the netbeans plugin: https://github.com/forge/netbeans-plugin/blob/master/ui/src/main/java/org/jboss/forge/netbeans/ui/context/NbUIContext.java#L63-L92

Wanna submit a PR?

**Comment by rmpestano** [comment]
Hi Geoge,
Sure! I AM travelling now but I will find a way to look at it.

Em sáb, 24 de out de 2015 11:03, George Gastaldi <notifications@github.com>
escreveu:

**Comment by rmpestano** [comment]
Hi @gastaldi, 

I've played a bit with intellij plugin. I have copied from netbeans plugin and call it in UIContextImpl constructor, see here: https://github.com/rmpestano/intellij-idea-plugin/commit/45757d714ecc0c0c3210153d6396ec20f4c81ead 

The next button got enabled with this modification (meaning that CommandScopedContext is active) but when I type something on any UIInput the input starts to blink, [here is a small vid](https://www.youtube.com/watch?v=aa9tVZKUksw&feature=youtu.be) showing this.    

When next button is clicked I got concurrentModification exception:

null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:123)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:96)
	at org.javassist.tmp.java.util.Iterator_$$_javassist_b2f939e7-a44d-448a-97e3-94ca7ba6bb77.next(Iterator_$$_javassist_b2f939e7-a44d-448a-97e3-94ca7ba6bb77.java)
	at org.jboss.forge.plugin.idea.ui.component.many.CheckBoxTableComponentBuilder$1.getInputValueChoices(CheckBoxTableComponentBuilder.java:124)
	at org.jboss.forge.plugin.idea.ui.component.many.CheckBoxTableComponentBuilder$1.updateState(CheckBoxTableComponentBuilder.java:85)
	at org.jboss.forge.plugin.idea.ui.listeners.ValueChangeListener.updateComponentsState(ValueChangeListener.java:50)
	at org.jboss.forge.plugin.idea.ui.wizard.ForgeWizardStep.prepare(ForgeWizardStep.java:79)
	at com.intellij.ui.wizard.WizardModel.b(WizardModel.java:173)
	at com.intellij.ui.wizard.WizardModel.a(WizardModel.java:91)
	at com.intellij.ui.wizard.WizardModel.next(WizardModel.java:76)
	at com.intellij.ui.wizard.WizardAction$Next.actionPerformed(WizardAction.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder.openWizard(CommandListPopupBuilder.java:224)
	at org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder.access$300(CommandListPopupBuilder.java:54)
	at org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder$3.run(CommandListPopupBuilder.java:173)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

any thoughts? I didnt had time to debug but looks like it has some conflict with changeListener

**Comment by gastaldi** [comment]
Interesting. Could you create a JIRA with this? I'll have a look asap

Em domingo, 25 de outubro de 2015, Rafael M. Pestano <
notifications@github.com> escreveu:

> Hi @gastaldi <https://github.com/gastaldi>,
>
> I've played a bit with intellij plugin. I have copied from netbeans plugin
> and call it in UIContextImpl constructor, see here:
> rmpestano/intellij-idea-plugin@45757d7
> <https://github.com/rmpestano/intellij-idea-plugin/commit/45757d714ecc0c0c3210153d6396ec20f4c81ead>
>
> The next button got enabled with this modification (meaning that
> CommandScopedContext is active) but when I type something on any UIInput
> the input starts to blink, here is a small vid
> <https://www.youtube.com/watch?v=aa9tVZKUksw&feature=youtu.be> showing
> this.
>
> When next button is clicked I got concurrentModification exception:
>
> null
> java.util.ConcurrentModificationException
> at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
> at java.util.ArrayList$Itr.next(ArrayList.java:851)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at
> org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:123)
> at
> org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
> at
> org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:96)
> at org.javassist.tmp.java.util.Iterator_$$
> *javassist_b2f939e7-a44d-448a-97e3-94ca7ba6bb77.next(Iterator*
> $$_javassist_b2f939e7-a44d-448a-97e3-94ca7ba6bb77.java)
> at
> org.jboss.forge.plugin.idea.ui.component.many.CheckBoxTableComponentBuilder$1.getInputValueChoices(CheckBoxTableComponentBuilder.java:124)
> at
> org.jboss.forge.plugin.idea.ui.component.many.CheckBoxTableComponentBuilder$1.updateState(CheckBoxTableComponentBuilder.java:85)
> at
> org.jboss.forge.plugin.idea.ui.listeners.ValueChangeListener.updateComponentsState(ValueChangeListener.java:50)
> at
> org.jboss.forge.plugin.idea.ui.wizard.ForgeWizardStep.prepare(ForgeWizardStep.java:79)
> at com.intellij.ui.wizard.WizardModel.b(WizardModel.java:173)
> at com.intellij.ui.wizard.WizardModel.a(WizardModel.java:91)
> at com.intellij.ui.wizard.WizardModel.next(WizardModel.java:76)
> at
> com.intellij.ui.wizard.WizardAction$Next.actionPerformed(WizardAction.java:46)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at
> javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> at
> javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> at
> javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> at java.awt.Component.processMouseEvent(Component.java:6535)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> at java.awt.Component.processEvent(Component.java:6300)
> at java.awt.Container.processEvent(Container.java:2236)
> at java.awt.Component.dispatchEventImpl(Component.java:4891)
> at java.awt.Container.dispatchEventImpl(Container.java:2294)
> at java.awt.Component.dispatchEvent(Component.java:4713)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> at java.awt.Container.dispatchEventImpl(Container.java:2280)
> at java.awt.Window.dispatchEventImpl(Window.java:2750)
> at java.awt.Component.dispatchEvent(Component.java:4713)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> at java.awt.EventQueue.access$500(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.awt.EventQueue$3.run(EventQueue.java:703)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> at
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> at java.awt.EventQueue$4.run(EventQueue.java:731)
> at java.awt.EventQueue$4.run(EventQueue.java:729)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
> at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> at
> java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
> at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
> at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
> at java.awt.Dialog.show(Dialog.java:1084)
> at
> com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
> at
> com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
> at
> com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
> at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
> at
> org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder.openWizard(CommandListPopupBuilder.java:224)
> at
> org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder.access$300(CommandListPopupBuilder.java:54)
> at
> org.jboss.forge.plugin.idea.ui.CommandListPopupBuilder$3.run(CommandListPopupBuilder.java:173)
> at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> at java.awt.EventQueue.access$500(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.awt.EventQueue$3.run(EventQueue.java:703)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> at
> java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at
> java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>
> any thoughts? I didnt had time to debug but looks like it has some
> conflict with changeListener
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmpestano/music-addon/issues/14#issuecomment-150992138>
> .
>


-- 
*George Gastaldi | Senior Software Engineer*

JBoss Forge Team
T: +55 11 3524-6169
M: +55 47 9711-1000

**Comment by rmpestano** [comment]
@gastaldi I've created issue [FORGE-2512](https://issues.jboss.org/browse/FORGE-2512)

**Comment by gastaldi** [comment]
Thanks! Also,feel free to submit a PR if you like :)
Em 26/10/2015 10:01, "Rafael M. Pestano" <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
I pushed some changes to the IDEA plugin. Can you test with the latest snapshot? I haven't been able to reproduce your issue. Except that I am seeing the following in the logs: 
    Oct 26, 2015 4:34:05 PM com.github.forge.addon.music.playlist.PlaylistManagerImpl parsePlaylist
    WARNING: Problems for parsing playlist - null - null
